name: Check YouTube Playlist

on:
  schedule:
    - cron: '*/10 * * * *'  # 每 10 分鐘執行一次
  workflow_dispatch:  # 允許手動觸發工作流

jobs:
  check_playlist:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Fetch and parse YouTube RSS Feed
        run: |
          # 使用 curl 下載 YouTube 播放清單的 RSS feed
          curl -s https://www.youtube.com/feeds/videos.xml?playlist_id=PLvNcWaQnjkK9Ay0lfQbObltjDcrT-ad6z > feed.xml

          # 使用 xmllint 來解析 XML 並提取最新影片的 videoId
          VIDEO_ID=$(xmllint --xpath "string(//entry[1]/yt:videoId)" feed.xml)

          # 檢查 videoId 是否有變化
          if [ "$VIDEO_ID" != "$(cat last_video_id.txt 2>/dev/null)" ]; then
            # 如果有新的影片，發送 Webhook
            curl -X POST -H "Content-Type: application/json" \
              -d "{\"videoId\": \"$VIDEO_ID\", \"videoTitle\": \"$(xmllint --xpath 'string(//entry[1]/title)' feed.xml)\"}" \
              http://yourdomain.com/webhook
            
            # 儲存最新的 videoId
            echo $VIDEO_ID > last_video_id.txt
          else
            echo "沒有新影片"
          fi
