name: Check YouTube Playlist

on:
  schedule:
    - cron: '*/10 * * * *'  # 每 10 分鐘執行一次
  workflow_dispatch:  # 允許手動觸發工作流

jobs:
  check_playlist:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        
      - name: Install xmllint
        run: |
          sudo apt-get update
          sudo apt-get install -y xmlstarlet
          sudo apt-get install -y libxml2-utils
      
      - name: Fetch and parse YouTube RSS Feed
        run: |
          # 使用 curl 下載 YouTube 播放清單的 RSS feed
          curl -s https://www.youtube.com/feeds/videos.xml?playlist_id=PLvNcWaQnjkK9Ay0lfQbObltjDcrT-ad6z > feed.xml

          # 使用 xmllint 來解析 XML 並提取最新影片的相關資訊
          VIDEO_ID=$(xmllint --xpath "string(//entry[1]/yt:videoId)" --namespace-uris "http://www.youtube.com/xml/schemas/2015" feed.xml)
          VIDEO_TITLE=$(xmllint --xpath "string(//entry[1]/title)" feed.xml)
          VIDEO_CHANNEL_TITLE=$(xmllint --xpath "string(//entry[1]/author/name)" feed.xml)
          VIDEO_DESCRIPTION=$(xmllint --xpath "string(//entry[1]/summary)" feed.xml)
          VIDEO_THUMBNAIL=$(xmllint --xpath "string(//entry[1]/media:group/media:thumbnail/@url)" --namespace-uris "http://search.yahoo.com/mrss/" feed.xml)
          VIDEO_PUBLISHED_AT=$(xmllint --xpath "string(//entry[1]/published)" feed.xml)

          # 檢查 videoId 是否有變化
          if [ "$VIDEO_ID" != "$(cat last_video_id.txt 2>/dev/null)" ]; then
            # 如果有新影片，發送 Webhook
            curl -X POST -H "Content-Type: application/json" \
              -d "{
                \"videoId\": \"$VIDEO_ID\",
                \"videoTitle\": \"$VIDEO_TITLE\",
                \"videoChannelTitle\": \"$VIDEO_CHANNEL_TITLE\",
                \"videoDescription\": \"$VIDEO_DESCRIPTION\",
                \"videoThumbnail\": \"$VIDEO_THUMBNAIL\",
                \"videoPublishedAt\": \"$VIDEO_PUBLISHED_AT\"
              }" \
              http://yourdomain.com/webhook
            
            # 儲存最新的 videoId
            echo $VIDEO_ID > last_video_id.txt
          else
            echo "沒有新影片"
          fi
